package com.gymchin.api.common.error;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    AUTH_UNAUTHORIZED,
    VALIDATION_FAILED,
    RESOURCE_NOT_FOUND,
    MATCH_ALREADY_REQUESTED,
    MATCH_ALREADY_CONNECTED,
    MATCH_INVALID_STATE,
    CONFLICT,
    INTERNAL_ERROR
}
