DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS matchings CASCADE;
DROP TABLE IF EXISTS user_preferred_time_slots CASCADE;
DROP TABLE IF EXISTS user_preferred_days CASCADE;
DROP TABLE IF EXISTS user_goals CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;
